Fix a sat mapper bug
qiskit-community/qopt-best-practices pull request #29
Opened 2024-03-18 01:57 UTC by a-matsuo

### Summary
Fix #23

### Details and comments
The SAT mapper did not compute the state of full connectivity, which should be (n-2). It only calculated up to (n-3).
Therefore, it raised an error for instances requiring full connectivity.

2024-03-18 06:36 UTC, ElePT reviewed
LGTM! I added a tiny comment

2024-03-18 06:36 UTC, ElePT commented on test/test_sat_mapping.py
> +        graph = nx.random_regular_graph(3, 6, seed=1)  # fails
```suggestion
        graph = nx.random_regular_graph(3, 6, seed=1)
```

2024-03-18 06:54 UTC, a-matsuo commented on test/test_sat_mapping.py
> +        graph = nx.random_regular_graph(3, 6, seed=1)  # fails
Thank you for pointing it out!

2024-03-18 08:00 UTC, eggerdj requested changes
Thanks Atsushi. Can we try and also cover the case of defective SWAP strategies, i.e., SWAP strategies that, no matter the number of layers, cannot reach full connectivity?

2024-03-18 09:50 UTC, a-matsuo commented on qopt_best_practices/sat_mapping/sat_mapper.py
>          edge_map = dict(results[min_k].mapping)
I understand. I have updated it to return None, None, None when the SAT mapper is unable to find solutions.

2024-03-18 12:36 UTC, ElePT commented on qopt_best_practices/sat_mapping/sat_mapper.py
>          edge_map = dict(results[min_k].mapping)
I think that returning `None, None, None` might be nicer to handle for users, as long as the behavior is clearly explained in the class docstring, so maybe that needs to be updated too?

2024-03-19 03:14 UTC, a-matsuo commented on qopt_best_practices/sat_mapping/sat_mapper.py
>          edge_map = dict(results[min_k].mapping)
Thank you for your comment! Yes, we definitely need to update the docstring. I will work on that.

2024-03-21 09:54 UTC, eggerdj reviewed
This looks good to me now. I have one last comment.

2024-03-21 09:54 UTC, eggerdj commented on test/test_sat_mapping.py
> +        swap_strategy = SwapStrategy(cmap, [])
```suggestion
        graph = nx.random_regular_graph(3, 6, seed=1)
        cmap = CouplingMap([(idx, idx + 1) for idx in range(5)])
        swap_strategy = SwapStrategy(cmap, [])
```
Looks like the first swap strat is redundent

2024-03-22 08:02 UTC, eggerdj approved these changes
LGTM. Thanks a lot. Please fix whatever is failing in CI.

2024-03-22 08:30 UTC, merged